### ISSUE TITLE
bufstats crash when sending buffer message to right inlet

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-pd#62]
as in this patch's 2nd tab (musical example) when one sends the buffer message to the right (weighting) inlet, it crashes.

[fluid.bufstats-help CRASH.pd.zip](https://github.com/flucoma/flucoma-pd/files/8909670/fluid.bufstats-help.CRASH.pd.zip)

**Comment by weefuzzy** [comment]
Once again we see that I can't count. This should be fixed by commit 9b5e65b86361f5cb8f7feefc82997d7a47ca0efd. 

I note that the example doesn't actually work yet, because apparently the weights are invalid, but unfortunately the warning associated with that gets swallowed (which, IIRC, it doesn't on Max). But that's separate problem.

**Comment by tremblap** [comment]
fixed thanks
